services:
  api:
    build: .
    container_name: api-sumarizacao
    ports:
      - "8000:8000"
    volumes:
      - /home/vitor.oliveira/Downloads/estudo/git-demo/Projeto/dados_estacao.duckdb:/app/dados_estacao.duckdb
    # Configuração MCP atualizada para usar localhost dentro do container

